version: "3"

services:
  instability:
    image: sndnv/instability
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - DATA_STORE=/opt/instability/data/store.db
      - SERVICE_HOST=0.0.0.0
      - PROMETHEUS_HOST=0.0.0.0
      - LATENCY_COLLECTION_INTERVAL=30
      - LATENCY_TARGETS=localhost,192.168.1.1,8.8.8.8,google.com
    volumes:
      - ./data:/opt/instability/data
    restart: always
    networks:
      - default

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    restart: always
    networks:
      - default

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    networks:
      - default

networks:
  default:

volumes:
  prometheus_data:
